### ISSUE TITLE
Encoding Issues

### ISSUE THREAD

**Issue by hanyoonLDA** [SeaHOH/ban-peers#7]
Hi guys, great job with the script. The script was working fine the first run, then it began to give decoding errors every time I try to run the script. 

```
16:18:51 Auto-banning script start running
16:18:51 Error occurred: 'utf-8' codec can't decode byte 0xd7 in position 12990: invalid continuation byte
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\ban_peers\__init__.py", line 1152, in run
    self.check_peers()
  File "c:\python38\lib\site-packages\ban_peers\__init__.py", line 830, in check_peers
    for torrent in self.get_torrents():
  File "c:\python38\lib\site-packages\ban_peers\__init__.py", line 712, in get_torrents
    torrents = json.load(self.request(params=self._params_list))
  File "C:\Python38\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python38\Lib\json\__init__.py", line 343, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 12990: invalid continuation byte
16:19:01 Error occurred: 'utf-8' codec can't decode byte 0xd7 in position 12984: invalid continuation byte
```

Any idea what could be causing this? I'm trying to trace back to where the issue is occuring, but everything looks good to me. Not sure what's going on to be honest. Could it be some rogue characters inside the torrent names that are causing this?

**Comment by hanyoonLDA** [comment]
Very weird -- WebUI was working fine in browser earlier. Now it says "invalid request." Tried changing ports, restarted the client, and tried localhost. 

```
GET / HTTP/1.1
Host: 127.0.0.1:2647
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
DNT: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

Response: `invalid request`

**Comment by SeaHOH** [comment]
> Response: `invalid request`

The URI path is `/gui/`.

**Comment by hanyoonLDA** [comment]
Same result. Re-installing client now. Hopefully my BTT wallet remains.

**Comment by hanyoonLDA** [comment]
Okay, GUI is back, but BTT Speed is gone. Any idea how to get it back? I ran `helper_web_ui.btinstall` in the data folder earlier, that's when it disappeared 😅

**Comment by SeaHOH** [comment]
No idea. I do not use wallet.

**Comment by hanyoonLDA** [comment]
Wallet aside, the encoding issue still remains. Removed all torrents and added a fresh torrent to check as well. Let me try to debug this a bit.

**Comment by hanyoonLDA** [comment]
Deleted all torrents and attempted to launch -- same encoding error.
Deleted all torrents, plus the config file generated from earlier -- same encoding error.

Is there a cache somewhere?

**Comment by hanyoonLDA** [comment]
fp.read:

```
b'{"build":45988,"torrents": [\n],\n"label": [],"torrentc": "122800072"\n,"rssfeeds": [\n[2,true,true,false,false,0,"
...
...
```


```    if isinstance(s, str):
        if s.startswith('\ufeff'):
            raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
                                  s, 0)
    else:
        if not isinstance(s, (bytes, bytearray)):
            raise TypeError(f'the JSON object must be str, bytes or bytearray, '
                            f'not {s.__class__.__name__}')
        try:
            s = s.decode(detect_encoding(s), 'surrogatepass')
        except Exception as e:
            print(e)
```

```
19:14:40 Error occurred: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\ban_peers\__init__.py", line 1152, in run
    self.check_peers()
  File "C:\Python38\lib\site-packages\ban_peers\__init__.py", line 830, in check_peers
    for torrent in self.get_torrents():
  File "C:\Python38\lib\site-packages\ban_peers\__init__.py", line 712, in get_torrents
    torrents = json.load(self.request(params=self._params_list))
  File "C:\Python38\Lib\json\__init__.py", line 294, in load
    return loads(fp.read(),
  File "C:\Python38\Lib\json\__init__.py", line 361, in loads
    return _default_decoder.decode(s)
  File "C:\Python38\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):top, (R)estart, (P)ause/Proceed
  File "C:\Python38\Lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\Lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\ban_peers\__main__.py", line 6, in <module>
    ban_peers.main()
  File "C:\Python38\lib\site-packages\ban_peers\__init__.py", line 1544, in main
    ut.run(utp)
  File "C:\Python38\lib\site-packages\ban_peers\__init__.py", line 1220, in run
    time.sleep(2)
KeyboardInterrupt
```

**Comment by hanyoonLDA** [comment]
https://i.imgur.com/56aPghn.png

Works perfectly on my other machine (with the same torrents). Not worth the headache. Going to reinstall Python and set up proper env and hope it works on local machine.

**Comment by SeaHOH** [comment]
When you have resolved the issue, I would like to hear the background stroy, have a good luck!
